//! The TypeScript side of bise-proto: `apps/desktop/src/proto/*.ts`, made
//! from the Rust types with ts-rs (feature `ts`, so bise and sb never
//! compile ts-rs), never hand-edited (architect m_9476).
//!
//! - one `.ts` per wire module (hub, draft, thread, rows, diff, ops,
//!   context, helper, pty) + `json.ts` (serde_json's Value) + `index.ts`;
//! - `fixtures.gen.ts`: every fixture line as a typed constant, so
//!   `pnpm typecheck` fails when a fixture doesn't fit its generated type;
//! - u64/i64 come out as `number` (ids, positions, `*_ms`: safe below 2^53),
//!   an omitted field (`default` + `skip_serializing_if`) as `field?: T`, an
//!   `Option` written as null as `T | null`, the `Unknown { tag, raw }`
//!   variants not at all (`serde(skip)`: the store handles unknown tags).
//!
//! `cargo test -p bise-proto --features ts --test ts` fails when a file is
//! stale; `BISE_PROTO_BLESS=1` writes them.
#![cfg(feature = "ts")]

use bise_proto::{commands, context, diff, draft, helper, hub, ops, pty, rows, rpc, thread};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;
use std::path::{Path, PathBuf};
use ts_rs::{Config, TS};

const BLESS: &str = "BISE_PROTO_BLESS";

fn header(s: &mut String) {
    writeln!(s, "// generated by bise-proto (rust/proto/tests/ts.rs), never hand-edited:").unwrap();
    writeln!(s, "// {BLESS}=1 cargo test -p bise-proto --features ts --test ts").unwrap();
    writeln!(s, "// ids, positions and *_ms are numbers (u64 in Rust, safe below 2^53).").unwrap();
}

/// One declared type: its TS name, its declaration, its docs, the names it uses.
struct Decl {
    name: String,
    decl: String,
    docs: Option<String>,
    deps: Vec<String>,
}

fn decl<T: TS + 'static + ?Sized>(cfg: &Config) -> Decl {
    Decl {
        name: T::ident(cfg),
        decl: T::decl(cfg),
        docs: T::docs(),
        deps: T::dependencies(cfg).into_iter().map(|d| d.ts_name).collect(),
    }
}

macro_rules! module {
    ($cfg:expr, $file:literal: $($t:ty),+ $(,)?) => {
        ($file, vec![$(decl::<$t>($cfg)),+])
    };
}

/// Every wire type, by the module (and so the .ts file) it lives in.
fn modules(cfg: &Config) -> Vec<(&'static str, Vec<Decl>)> {
    vec![
        module!(cfg, "json": serde_json::Value),
        module!(cfg, "context": context::FnContext),
        module!(cfg, "diff": diff::LineKind, diff::DiffLine, diff::Hunk, diff::DiffFile, diff::DiffResult, diff::Series, diff::DiffView),
        module!(cfg, "rows": rows::Status, rows::Phase, rows::ReportKind, rows::Report, rows::Agent, rows::Opt, rows::CardPage, rows::Card, rows::Merged, rows::DevServer, rows::Worktree, rows::FeatureTry, rows::Feature, rows::PrState, rows::PrChecks, rows::PrReview, rows::Pr, rows::Place, rows::ModelRole, rows::Model, rows::Artifact, rows::ArtifactPr, rows::ArtifactVersion, rows::ScheduledTask, rows::ScheduledEnd, rows::AgentUsage, rows::WaitingOn, rows::AgentMode, rows::Changes, rows::FlowMode, rows::ApprovalMode, rows::CheckerKind, rows::ApprovalRule),
        module!(cfg, "thread": thread::EntryKind, thread::ToolKind, thread::ToolState, thread::FileCount, thread::ToolItem, thread::Tools, thread::EntryCard, thread::PageRef, thread::ReportRef, thread::Thinking, thread::Delivery, thread::NoticeLevel, thread::Notice, thread::NotDelivered, thread::Landed, thread::PrNewsState, thread::PrNews, thread::Made, thread::ImageRef, thread::Answered, thread::ApprovalFold, thread::Scheduled, thread::TurnFailed, thread::Entry),
        module!(cfg, "ops": ops::BranchRow, ops::VersionItem, ops::ReleaseEv),
        module!(cfg, "hub": hub::JobState, hub::Job, hub::HubEv, hub::Mode, hub::SendOpts, hub::HubCmd, hub::ErrorKind),
        module!(cfg, "rpc": rpc::Id, rpc::Request, rpc::Notification, rpc::Response, rpc::ErrorData, rpc::RpcError, rpc::Watermark, rpc::ClientInfo, rpc::InitializeParams, rpc::HubState, rpc::InitializeResult, rpc::CommandsList, rpc::CommandRunResult),
        module!(cfg, "commands": commands::WordRow, commands::ArgRow, commands::CommandRow),
        module!(cfg, "draft": draft::Quote, draft::Queued, draft::DraftHubCmd, draft::ProjectRow, draft::OpenWhat, draft::Account, draft::Found, draft::AwayProject, draft::Plugin, draft::PluginLogin, draft::CuRow, draft::RoleRow, draft::Runs, draft::PickChoice, draft::PickArg, draft::PickCommand, draft::PickSkill, draft::PickFile, draft::PickFolder, draft::CoreEv, draft::AppCmd, draft::TalkPage, draft::ProjectView, draft::IndexRow),
        module!(cfg, "helper": helper::HelperEv, helper::Responsible, helper::FnAct, helper::TalkKey, helper::Grant, helper::QuietWhy, helper::Perm, helper::PermAction, helper::HelperCmd),
        module!(cfg, "pty": pty::PtyEv, pty::PtyCmd),
    ]
}

/// A fixture file, the generated type each of its lines must fit, and its module.
/// (unknown.jsonl is left out on purpose: its tags are unknown by design.)
const FIXTURES: &[(&str, &str, &str)] = &[
    ("hub_ev.jsonl", "HubEv", "hub"),
    ("hub_cmd.jsonl", "HubCmd", "hub"),
    ("core_ev.jsonl", "CoreEv", "draft"),
    ("app_cmd.jsonl", "AppCmd", "draft"),
    ("draft_hub_cmd.jsonl", "DraftHubCmd", "draft"),
    ("project_view.json", "ProjectView", "draft"),
    ("context.jsonl", "FnContext", "context"),
    ("helper_ev.jsonl", "HelperEv", "helper"),
    ("helper_cmd.jsonl", "HelperCmd", "helper"),
    ("pty_ev.jsonl", "PtyEv", "pty"),
    ("pty_cmd.jsonl", "PtyCmd", "pty"),
    ("command_run_result.jsonl", "CommandRunResult", "rpc"),
];

fn proto_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../apps/desktop/src/proto")
}

fn render_module(file: &str, decls: &[Decl], home: &BTreeMap<String, &'static str>) -> String {
    let mut imports: BTreeMap<&str, BTreeSet<&str>> = BTreeMap::new();
    for d in decls {
        for dep in &d.deps {
            let from = home.get(dep).unwrap_or_else(|| panic!("{}: uses {dep}, which no module of tests/ts.rs declares", d.name));
            if *from != file {
                imports.entry(from).or_default().insert(dep);
            }
        }
    }
    let mut s = String::new();
    header(&mut s);
    if !imports.is_empty() {
        writeln!(s).unwrap();
    }
    for (from, names) in &imports {
        let names: Vec<&str> = names.iter().copied().collect();
        writeln!(s, "import type {{ {} }} from './{from}';", names.join(", ")).unwrap();
    }
    for d in decls {
        writeln!(s).unwrap();
        if let Some(docs) = &d.docs {
            writeln!(s, "{}", docs.trim_end()).unwrap();
        }
        writeln!(s, "export {}", d.decl).unwrap();
    }
    s
}

fn fixture_values(file: &str) -> Vec<serde_json::Value> {
    let p = Path::new(env!("CARGO_MANIFEST_DIR")).join("fixtures").join(file);
    let text = std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("{}: {e}", p.display()));
    let parse = |l: &str| serde_json::from_str(l).unwrap_or_else(|e| panic!("{file}: {e}: {l}"));
    if file.ends_with(".json") {
        return vec![parse(&text)];
    }
    text.lines().filter(|l| !l.trim().is_empty()).map(parse).collect()
}

fn render_fixtures() -> String {
    let mut s = String::new();
    header(&mut s);
    writeln!(s, "// every line of rust/proto/fixtures, typed: a fixture that doesn't fit its type fails pnpm typecheck.").unwrap();
    writeln!(s).unwrap();
    let mut by_module: BTreeMap<&str, BTreeSet<&str>> = BTreeMap::new();
    for (_, ty, module) in FIXTURES {
        by_module.entry(module).or_default().insert(ty);
    }
    for (module, tys) in &by_module {
        let tys: Vec<&str> = tys.iter().copied().collect();
        writeln!(s, "import type {{ {} }} from './{module}';", tys.join(", ")).unwrap();
    }
    for (file, ty, _) in FIXTURES {
        let name = file.split('.').next().unwrap_or(file);
        writeln!(s).unwrap();
        writeln!(s, "/** rust/proto/fixtures/{file} */").unwrap();
        writeln!(s, "export const {name}: readonly {ty}[] = [").unwrap();
        for v in fixture_values(file) {
            writeln!(s, "  {v},").unwrap();
        }
        writeln!(s, "];").unwrap();
    }
    s
}

/// The JSON-RPC tables (bise_proto::rpc): each method's HubCmd tag and
/// result HubEv tag, each notification's HubEv tag and scope, so the
/// window's client maps them from the same owner (architect m_13089).
fn render_methods() -> String {
    let mut s = String::new();
    header(&mut s);
    writeln!(s, "// bise_proto::rpc's tables: a method's params are its HubCmd's fields, a notification's its HubEv's.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "export const PROTO = {};", bise_proto::PROTO).unwrap();
    writeln!(s, "export const OWN_METHODS = [{}] as const;", rpc::OWN_METHODS.iter().map(|m| format!("{m:?}")).collect::<Vec<_>>().join(", ")).unwrap();
    writeln!(s).unwrap();
    writeln!(s, "export const METHODS = {{").unwrap();
    for r in rpc::METHODS {
        let result = r.result.map_or("null".to_string(), |t| format!("{t:?}"));
        writeln!(s, "  {:?}: {{ cmd: {:?}, result: {result} }},", r.method, r.cmd).unwrap();
    }
    writeln!(s, "}} as const;").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "export const NOTIFICATIONS = {{").unwrap();
    for r in rpc::NOTIFICATIONS {
        let scope = format!("{:?}", r.scope).to_lowercase();
        writeln!(s, "  {:?}: {{ ev: {:?}, scope: {scope:?} }},", r.method, r.ev).unwrap();
    }
    writeln!(s, "}} as const;").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "// the methods whose result is its own type, not a HubEv's fields").unwrap();
    writeln!(s, "export const RESULTS = {{").unwrap();
    for (m, t) in rpc::OWN_RESULTS {
        writeln!(s, "  {m:?}: {t:?},").unwrap();
    }
    writeln!(s, "}} as const;").unwrap();
    s
}

fn render_all() -> BTreeMap<String, String> {
    let cfg = Config::new().with_large_int("number");
    let modules = modules(&cfg);
    let mut home = BTreeMap::new();
    for (file, decls) in &modules {
        for d in decls {
            assert!(home.insert(d.name.clone(), *file).is_none(), "{} is declared twice", d.name);
        }
    }
    let mut out = BTreeMap::new();
    let mut index = String::new();
    header(&mut index);
    writeln!(index).unwrap();
    for (file, decls) in &modules {
        out.insert(format!("{file}.ts"), render_module(file, decls, &home));
        writeln!(index, "export type * from './{file}';").unwrap();
    }
    out.insert("index.ts".to_string(), index);
    out.insert("fixtures.gen.ts".to_string(), render_fixtures());
    out.insert("methods.gen.ts".to_string(), render_methods());
    out
}

#[test]
fn the_typescript_types_are_fresh() {
    let dir = proto_dir();
    // a checkout without the desktop app (main's desktop-hub, architect
    // m_11797): nothing to compare against; the types still render below
    let desktop = dir.parent().and_then(Path::parent).is_some_and(Path::is_dir);
    if !desktop && std::env::var_os(BLESS).is_none() {
        assert!(!render_all().is_empty());
        eprintln!("no apps/desktop here: the TypeScript files are not compared");
        return;
    }
    let want = render_all();
    let present: Vec<String> = std::fs::read_dir(&dir)
        .map(|rd| rd.filter_map(|e| e.ok()).map(|e| e.file_name().to_string_lossy().to_string()).filter(|n| n.ends_with(".ts")).collect())
        .unwrap_or_default();
    if std::env::var_os(BLESS).is_some_and(|v| v == "1") {
        std::fs::create_dir_all(&dir).unwrap();
        for name in present.iter().filter(|n| !want.contains_key(*n)) {
            std::fs::remove_file(dir.join(name)).unwrap();
        }
        for (name, text) in &want {
            std::fs::write(dir.join(name), text).unwrap();
        }
        return;
    }
    let mut stale: Vec<String> = want
        .iter()
        .filter(|(name, text)| std::fs::read_to_string(dir.join(name)).ok().as_deref() != Some(text.as_str()))
        .map(|(name, _)| name.clone())
        .collect();
    stale.extend(present.iter().filter(|n| !want.contains_key(*n)).map(|n| format!("{n} (not generated)")));
    assert!(stale.is_empty(), "apps/desktop/src/proto is stale: {stale:?}; run {BLESS}=1 cargo test -p bise-proto --features ts --test ts");
}

#[test]
fn omitted_fields_are_optional_and_ids_are_numbers() {
    let cfg = Config::new().with_large_int("number");
    // Hello's typed_only: default + skip_serializing_if, so absent on the wire
    let cmd = hub::HubCmd::decl(&cfg);
    assert!(cmd.contains("typed_only?: boolean"), "{cmd}");
    // Thread's before: an Option written as null when there is none
    let ev = hub::HubEv::decl(&cfg);
    assert!(ev.contains("before: number | null"), "{ev}");
    assert!(!ev.contains("bigint"), "{ev}");
    // the Unknown variants are not in the TS
    assert!(!ev.contains("\"unknown\"") && !ev.contains("raw:"), "{ev}");
}
